version: "3.1"
 
services:
  db:
    image: mysql:9.2
    ports:
      - 3306:3306
    restart: "no"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./sqlfiles:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h localhost
 
  adminer:
    image: adminer
    restart: "no"
    ports:
      - 8080:8080
 
  python:
    image: python-image
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/src
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    restart: "on-failure"

 
volumes:
  migrations: